In [1]:
import numpy as np
import pandas as pd
import cv2

In [2]:
df=pd.read_csv('D:\Datasets\Alphabet_Recognition\A_Z Handwritten Data.csv')

In [3]:
df

,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,...,0.639,0.640,0.641,0.642,0.643,0.644,0.645,0.646,0.647,0.648
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372445,25,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
372446,25,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
372447,25,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
372448,25,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
372449,25,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
y=df['0']

In [5]:
X=df.drop('0',axis=1)

In [6]:
X

,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.10,...,0.639,0.640,0.641,0.642,0.643,0.644,0.645,0.646,0.647,0.648
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372445,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
372446,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
372447,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
372448,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
372449,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
X.shape

(372450, 784)

In [8]:
X=X.values.reshape(372450,28,28)/255

In [9]:
X.shape

(372450, 28, 28)

In [10]:
from tensorflow.keras.utils import to_categorical

In [11]:
y=to_categorical(y)

In [12]:
y

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [13]:
y.shape

(372450, 26)

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Flatten,Dense

In [15]:
model=Sequential()
model.add(Conv2D(16,(3,3),activation='relu',input_shape=(28,28,1)))
model.add(MaxPool2D())
model.add(Conv2D(32,(3,3),activation='relu'))
model.add(MaxPool2D())
model.add(Conv2D(64,(3,3),activation='relu'))
model.add(Flatten())
model.add(Dense(26,activation='softmax'))

model.compile(loss='categorical_crossentropy',metrics=['accuracy'])

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d (Conv2D)             (None, 26, 26, 16)        160

 max_pooling2d (MaxPooling2D  (None, 13, 13, 16)       0
 )

 conv2d_1 (Conv2D)           (None, 11, 11, 32)        4640

 max_pooling2d_1 (MaxPooling  (None, 5, 5, 32)         0
 2D)

 conv2d_2 (Conv2D)           (None, 3, 3, 64)          18496

 flatten (Flatten)           (None, 576)               0

 dense (Dense)               (None, 26)                15002

=================================================================
Total params: 38,298
Trainable params: 38,298
Non-trainable params: 0
_________________________________________________________________

In [17]:
model.fit(X,y,batch_size=32,epochs=15)

Epoch 1/15
11640/11640 [==============================] - 112s 10ms/step - loss: 0.1314 - accuracy: 0.9636
Epoch 2/15
11640/11640 [==============================] - 120s 10ms/step - loss: 0.0821 - accuracy: 0.9787
Epoch 3/15
11640/11640 [==============================] - 94s 8ms/step - loss: 0.0891 - accuracy: 0.9773
Epoch 4/15
11640/11640 [==============================] - 94s 8ms/step - loss: 0.0965 - accuracy: 0.9759
Epoch 5/15
11640/11640 [==============================] - 96s 8ms/step - loss: 0.1029 - accuracy: 0.9748
Epoch 6/15
11640/11640 [==============================] - 95s 8ms/step - loss: 0.1103 - accuracy: 0.9738
Epoch 7/15
11640/11640 [==============================] - 102s 9ms/step - loss: 0.1171 - accuracy: 0.9727
Epoch 8/15
11640/11640 [==============================] - 105s 9ms/step - loss: 0.1217 - accuracy: 0.9720
Epoch 9/15
11640/11640 [==============================] - 106s 9ms/step - loss: 0.1320 - accuracy: 0.9705
Epoch 10/15
11640/11640 [==============================] - 130s 11ms/step - loss: 0.1466 - accuracy: 0.9681
Epoch 11/15
11640/11640 [==============================] - 129s 11ms/step - loss: 0.1526 - accuracy: 0.9670
Epoch 12/15
11640/11640 [==============================] - 129s 11ms/step - loss: 0.1502 - accuracy: 0.9672
Epoch 13/15
11640/11640 [==============================] - 115s 10ms/step - loss: 0.1565 - accuracy: 0.9660
Epoch 14/15
11640/11640 [==============================] - 100s 9ms/step - loss: 0.1716 - accuracy: 0.9643
Epoch 15/15
11640/11640 [==============================] - 104s 9ms/step - loss: 0.1736 - accuracy: 0.9636

In [18]:
model.save('AlphabetCNN.h5')

# Model Testing

In [19]:
alphabets=[]
for i in range(97,123):
    alphabets.append(chr(i))

In [22]:
print(alphabets)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

In [75]:
j=120900
inp=X[j]
print('actual alphabet is '+alphabets[y[j].argmax()])

actual alphabet is n

In [76]:
inp=inp.reshape(1,28,28)

In [77]:
alpha=(model.predict(inp)).argmax()

1/1 [==============================] - 0s 17ms/step

In [78]:
print('Predicted alphabet is '+alphabets[alpha])

Predicted alphabet is n